const commonConstants = {
  PASSWORD_VALIDITY_DAYS: 30,
  SPECIFIED_EVENT_VALUE: '指定したイベントの閲覧が可能',
  APP_MODAL_DEMO_DATA_LENGTH: 16,
  INPUT_PLACEHOLDER_PREFIX: (placeholder) => `${placeholder}を入力してください`, //Please enter   
  INPUT_PLACEHOLDER_PREFIX_SELECT: (placeholder) => `${placeholder}を選択してください`, //Please choose 
}
export default commonConstants;

export const DIVIDER_TEXT_MAX_LENGTH = 8;

export const appDesignerSettingPages = [
  { id: 1, key: 'faviconSettings', title: 'faviconデザイン', adminJSX: 'FavIconUploader' },
  { id: 3, key: 'pageFrameSettings', title: 'ページフレームデザイン', adminJSX: 'PageFrameSettingsForm' },
  { id: 4, key: 'logoSettings', title: 'ヘッダーロゴデザイン', adminJSX: 'LogoSettngs' },
  { id: 5, key: 'footerSettings', title: 'フッターデザイン', adminJSX: 'FooterSettings' },
  { id: 6, key: 'step1Settings', title: 'ステップタイプ１デザイン', adminJSX: 'Step1Settings' },
  { id: 7, key: 'step2Settings', title: 'ステップタイプ2デザイン', adminJSX: 'Step1Settings' },
  { id: 8, key: 'step3Settings', title: 'ステップタイプ3デザイン', adminJSX: 'Step1Settings' },
  { id: 9, key: 'informationAreaSttings', title: '情報エリアデザイン', adminJSX: 'SettingInformationForm' },
  { id: 10, key: 'buttonASettings', title: 'ボタンAデザイン', adminJSX: 'ButtonSettingsForm' },
  { id: 11, key: 'buttonBSettings', title: 'ボタンBデザイン', adminJSX: 'ButtonSettingsForm' },
  { id: 12, key: 'buttonCSettings', title: 'ボタンCデザイン', adminJSX: 'ButtonSettingsForm' },
  { id: 13, key: 'h1Settings', title: '見出しH1デザイン', adminJSX: 'H1Settings' },
  { id: 14, key: 'h2Settings', title: '見出しH2デザイン', adminJSX: 'H1Settings' },
  { id: 15, key: 'h3Settings', title: '見出しH3デザイン', adminJSX: 'H1Settings' },
  { id: 16, key: 'h4Settings', title: '見出しH4デザイン', adminJSX: 'H1Settings' },
  { id: 17, key: 'h5Settings', title: '見出しH5デザイン', adminJSX: 'H1Settings' },
  { id: 18, key: 'h6Settings', title: '見出しH6デザイン', adminJSX: 'H1Settings' },
  // { id: 19, key: 'combinInputTextSettings', title: '結合入力フォームデザイン', adminJSX: 'FieldFormSettings' },
  { id: 522, key: 'zipSearchSettings', title: '郵便番号検索デザイン', adminJSX: 'ZipSearchSettingsForm' },
  { id: 20, key: 'inputTextSettings', title: '入力フォームinputTextデザイン', adminJSX: 'FieldFormSettings' },
  { id: 21, key: 'inputDateSettings', title: '入力フォームinputDateデザイン', adminJSX: 'FieldFormSettings' },
  { id: 22, key: 'inputBirthdaySettings', title: '入力フォーム誕生日デザイン', adminJSX: 'InputBirthdaySettingsForm' },
  { id: 23, key: 'inputTimeSettings', title: '入力フォームinputTimeデザイン', adminJSX: 'FieldFormSettings' },
  { id: 24, key: 'inputNumberSettings', title: '入力フォームinputNumberデザイン', adminJSX: 'FieldFormSettings' },
  { id: 25, key: 'textareaFormSettings', title: '入力フォームtextareaデザイン', adminJSX: 'FieldFormSettings' },
  { id: 26, key: 'selectFormSettings', title: '入力フォームselectデザイン', adminJSX: 'FieldFormSettings' },
  { id: 27, key: 'radioAFormSettings', title: '入力フォームradioAデザイン', adminJSX: 'FieldFormRadioSettings' },
  { id: 28, key: 'radioBFormSettings', title: '入力フォームradioBデザイン', adminJSX: 'FieldFormSettings' },
  { id: 29, key: 'checkboxSettings', title: '入力フォームcheckboxデザイン', adminJSX: 'FieldFormSettings' },
  /*{ id: 30, key: 'eventSelection1Settings', title: 'イベント選択1デザイン', adminJSX: '' },
  { id: 31, key: 'eventSelection2Settings', title: 'イベント選択2デザイン', adminJSX: '' },
  { id: 32, key: 'eventSelection3Settings', title: 'イベント選択3デザイン', adminJSX: '' },*/

  { id: 33, key: 'categorySelection1Settings', title: 'カテゴリー選択1(北海道対がん協会検診選択タイプ)デザイン', adminJSX: '' },
  { id: 34, key: 'categorySelection2Settings', title: 'カテゴリー選択2(協会健保地域選択タイプ)デザイン', adminJSX: '' },
  // { id: 35, key: 'instituteSelection1Settings', title: '施設選択1(埼玉事前決定候補表示)デザイン', adminJSX: '' },
  { id: 36, key: 'instituteSelection2Settings', title: '施設選択デザイン', adminJSX: '' },

  { id: 40, key: 'slotSelection1Settings', title: 'スロット選択1(施設日時同時選択タイプ)デザイン', adminJSX: 'Slot1FormSettings' },
  { id: 41, key: 'slotSelection2Settings', title: 'スロット選択2(協会健保日時選択タイプ)デザイン', adminJSX: '' },
  /* { id: 42, key: 'slotSelection3Settings', title: 'スロット選択3デザイン', adminJSX: '' },*/
  { id: 43, key: 'itemSelection1Settings', title: 'アイテム選択デザイン', adminJSX: 'ItemSelection1Settings' },

  /*{ id: 44, key: 'token1loginSettings', title: '1トークンログインデザイン', adminJSX: 'Token1loginSettingsForm' },*/
  { id: 45, key: 'token2loginSettings', title: '2トークンログインデザイン(新規追加終了)', adminJSX: 'Token2loginSettingsForm' },
  { id: 46, key: 'token2loginType1Settings', title: '誕生日ログインデザイン', adminJSX: 'TwoTokenlogin1SettingsForm' },
  { id: 47, key: 'token2loginType2Settings', title: 'テキストログインデザイン', adminJSX: 'TwoTokenlogin2SettingsForm' },
  /*{ id: 46, key: 'token3loginSettings', title: '3トークンログインデザイン', adminJSX: 'Token2loginSettingsForm' },*/
  { id: 50, key: 'customCssSettings', title: 'カスタムCSSデザイン', adminJSX: 'CustomCssSettingsForm' },
  { id: 52, key: 'customColorSettings', title: 'カスタムカラー設定', adminJSX: 'CustomColorSettingForm' },
  { id: 53, key: 'checkboxIconSettings', title: 'カスタムチェックアイコンデザイン', adminJSX: 'CheckboxIconSettingForm' },
  { id: 54, key: 'customRadioIconSettings', title: 'カスタムラジオボタンアイコンデザイン', adminJSX: 'RadioboxIconSettingForm' },
  { id: 55, key: 'debugModeSettings', title: 'デバッグモード設定', adminJSX: 'DebugModeSettingsForm' },
  /*{ id: 37, key: 'busSelection1Settings', title: 'バス選択1デザイン', adminJSX: '' },
  { id: 38, key: 'busSelection2Settings', title: 'バス選択2デザイン', adminJSX: '' },
  { id: 39, key: 'busSelection3Settings', title: 'バス選択3デザイン', adminJSX: '' },*/
  { id: 60, key: 'duplicateAppDesignSettings', title: 'このAppに別のAppのデザインを上書きする', adminJSX: 'DuplicateAppDesignSettingsForm' },

]

export const fullWidthNumber = ["０", "１", "２", "３", "４", "５", "６", "７", "８", "９", "１０", "１１", "１２", "１３", "１４", "１５", "１６", "１７", "１８", "１９", "２０"];

export const paddingXArrays = [
  { caption: '左右：0px', value: 'px-0' },
  { caption: '左右：1px', value: 'px-px' },
  { caption: '左右：2px', value: 'px-0.5' },
  { caption: '左右：4px', value: 'px-1' },
  { caption: '左右：6px', value: 'px-1.5' },
  { caption: '左右：8px', value: 'px-2' },
  { caption: '左右：10px', value: 'px-2.5' },
  { caption: '左右：12px', value: 'px-3' },
  { caption: '左右：14px', value: 'px-3.5' },
  { caption: '左右：16px', value: 'px-4' },
  { caption: '左右：18px', value: 'px-5' },
  { caption: '左右：24px', value: 'px-6' },
  { caption: '左右：28px', value: 'px-7' },
  { caption: '左右：32px', value: 'px-8' },
  { caption: '左右：36px', value: 'px-9' },
  { caption: '左右：40px', value: 'px-10' },
  { caption: '左右：44px', value: 'px-11' },
  { caption: '左右：48px', value: 'px-12' },
  { caption: '左右：56px', value: 'px-14' },
  { caption: '左右：64px', value: 'px-16' },
  { caption: '左右：80px', value: 'px-20' },
  { caption: '左右：96px', value: 'px-24' },
  { caption: '左右：112px', value: 'px-28' },
  { caption: '左右：128px', value: 'px-32' },
  { caption: '左右：144px', value: 'px-36' },
  { caption: '左右：160px', value: 'px-40' },
  { caption: '左右：176px', value: 'px-44' },
  { caption: '左右：192px', value: 'px-48' },
  { caption: '左右：208px', value: 'px-52' },
  { caption: '左右：224px', value: 'px-56' },
  { caption: '左右：240px', value: 'px-60' },
  { caption: '左右：256px', value: 'px-64' },
  { caption: '左右：288px', value: 'px-72' },
  { caption: '左右：320px', value: 'px-80' },
  { caption: '左右：384px', value: 'px-96' },
];

export const paddingYArrays = [
  { caption: '上下：0px', value: 'py-0' },
  { caption: '上下：1px', value: 'py-px' },
  { caption: '上下：2px', value: 'py-0.5' },
  { caption: '上下：4px', value: 'py-1' },
  { caption: '上下：6px', value: 'py-1.5' },
  { caption: '上下：8px', value: 'py-2' },
  { caption: '上下：10px', value: 'py-2.5' },
  { caption: '上下：12px', value: 'py-3' },
  { caption: '上下：14px', value: 'py-3.5' },
  { caption: '上下：16px', value: 'py-4' },
  { caption: '上下：18px', value: 'py-5' },
  { caption: '上下：24px', value: 'py-6' },
  { caption: '上下：28px', value: 'py-7' },
  { caption: '上下：32px', value: 'py-8' },
  { caption: '上下：36px', value: 'py-9' },
  { caption: '上下：40px', value: 'py-10' },
  { caption: '上下：44px', value: 'py-11' },
  { caption: '上下：48px', value: 'py-12' },
  { caption: '上下：56px', value: 'py-14' },
  { caption: '上下：64px', value: 'py-16' },
  { caption: '上下：80px', value: 'py-20' },
  { caption: '上下：96px', value: 'py-24' },
  { caption: '上下：112px', value: 'py-28' },
  { caption: '上下：128px', value: 'py-32' },
  { caption: '上下：144px', value: 'py-36' },
  { caption: '上下：160px', value: 'py-40' },
  { caption: '上下：176px', value: 'py-44' },
  { caption: '上下：192px', value: 'py-48' },
  { caption: '上下：208px', value: 'py-52' },
  { caption: '上下：224px', value: 'py-56' },
  { caption: '上下：240px', value: 'py-60' },
  { caption: '上下：256px', value: 'py-64' },
  { caption: '上下：288px', value: 'py-72' },
  { caption: '上下：320px', value: 'py-80' },
  { caption: '上下：384px', value: 'py-96' },
]

export const marginTopArrays = [
  { caption: '上：0px', value: 'mt-0' },
  { caption: '上：1px', value: 'mt-px' },
  { caption: '上：2px', value: 'mt-0.5' },
  { caption: '上：4px', value: 'mt-1' },
  { caption: '上：6px', value: 'mt-1.5' },
  { caption: '上：8px', value: 'mt-2' },
  { caption: '上：10px', value: 'mt-2.5' },
  { caption: '上：12px', value: 'mt-3' },
  { caption: '上：14px', value: 'mt-3.5' },
  { caption: '上：16px', value: 'mt-4' },
  { caption: '上：18px', value: 'mt-5' },
  { caption: '上：24px', value: 'mt-6' },
  { caption: '上：28px', value: 'mt-7' },
  { caption: '上：32px', value: 'mt-8' },
  { caption: '上：36px', value: 'mt-9' },
  { caption: '上：40px', value: 'mt-10' },
  { caption: '上：44px', value: 'mt-11' },
  { caption: '上：48px', value: 'mt-12' },
  { caption: '上：56px', value: 'mt-14' },
  { caption: '上：64px', value: 'mt-16' },
  { caption: '上：80px', value: 'mt-20' },
  { caption: '上：96px', value: 'mt-24' },
  { caption: '上：112px', value: 'mt-28' },
  { caption: '上：128px', value: 'mt-32' },
  { caption: '上：144px', value: 'mt-36' },
  { caption: '上：160px', value: 'mt-40' },
  { caption: '上：176px', value: 'mt-44' },
  { caption: '上：192px', value: 'mt-48' },
  { caption: '上：208px', value: 'mt-52' },
  { caption: '上：224px', value: 'mt-56' },
  { caption: '上：240px', value: 'mt-60' },
  { caption: '上：256px', value: 'mt-64' },
  { caption: '上：288px', value: 'mt-72' },
  { caption: '上：320px', value: 'mt-80' },
  { caption: '上：384px', value: 'mt-96' },
  { caption: '上：自動', value: 'mt-auto' },
]

export const marginBottomArrays = [
  { caption: '下：0px', value: 'mb-0' },
  { caption: '下：1px', value: 'mb-px' },
  { caption: '下：2px', value: 'mb-0.5' },
  { caption: '下：4px', value: 'mb-1' },
  { caption: '下：6px', value: 'mb-1.5' },
  { caption: '下：8px', value: 'mb-2' },
  { caption: '下：10px', value: 'mb-2.5' },
  { caption: '下：12px', value: 'mb-3' },
  { caption: '下：14px', value: 'mb-3.5' },
  { caption: '下：16px', value: 'mb-4' },
  { caption: '下：18px', value: 'mb-5' },
  { caption: '下：24px', value: 'mb-6' },
  { caption: '下：28px', value: 'mb-7' },
  { caption: '下：32px', value: 'mb-8' },
  { caption: '下：36px', value: 'mb-9' },
  { caption: '下：40px', value: 'mb-10' },
  { caption: '下：44px', value: 'mb-11' },
  { caption: '下：48px', value: 'mb-12' },
  { caption: '下：56px', value: 'mb-14' },
  { caption: '下：64px', value: 'mb-16' },
  { caption: '下：80px', value: 'mb-20' },
  { caption: '下：96px', value: 'mb-24' },
  { caption: '下：112px', value: 'mb-28' },
  { caption: '下：128px', value: 'mb-32' },
  { caption: '下：144px', value: 'mb-36' },
  { caption: '下：160px', value: 'mb-40' },
  { caption: '下：176px', value: 'mb-44' },
  { caption: '下：192px', value: 'mb-48' },
  { caption: '下：208px', value: 'mb-52' },
  { caption: '下：224px', value: 'mb-56' },
  { caption: '下：240px', value: 'mb-60' },
  { caption: '下：256px', value: 'mb-64' },
  { caption: '下：288px', value: 'mb-72' },
  { caption: '下：320px', value: 'mb-80' },
  { caption: '下：384px', value: 'mb-96' },
  { caption: '下：自動', value: 'mb-auto' },
]

export const borderradiusArrays = [
  { caption: '4方向：なし', value: 'rounded-none' },
  { caption: '4方向：2px', value: 'rounded-sm' },
  { caption: '4方向：4px', value: 'rounded' },
  { caption: '4方向：6px', value: 'rounded-md' },
  { caption: '4方向：8px', value: 'rounded-lg' },
  { caption: '4方向：12px', value: 'rounded-xl' },
  { caption: '4方向：16px', value: 'rounded-2xl' },
  { caption: '4方向：24px', value: 'rounded-3xl' },
  { caption: '4方向：full', value: 'rounded-full' },
  { caption: '上方向：なし', value: 'rounded-t-none' },
  { caption: '上方向：2px', value: 'rounded-t-sm' },
  { caption: '上方向：4px', value: 'rounded-t' },
  { caption: '上方向：6px', value: 'rounded-t-md' },
  { caption: '上方向：8px', value: 'rounded-t-lg' },
  { caption: '上方向：12px', value: 'rounded-t-xl' },
  { caption: '上方向：16px', value: 'rounded-t-2xl' },
  { caption: '上方向：24px', value: 'rounded-t-3xl' },
  { caption: '上方向：full', value: 'rounded-t-full' },
  { caption: '右方向：なし', value: 'rounded-r-none' },
  { caption: '右方向：2px', value: 'rounded-r-sm' },
  { caption: '右方向：4px', value: 'rounded-r' },
  { caption: '右方向：6px', value: 'rounded-r-md' },
  { caption: '右方向：8px', value: 'rounded-r-lg' },
  { caption: '右方向：12px', value: 'rounded-r-xl' },
  { caption: '右方向：16px', value: 'rounded-r-2xl' },
  { caption: '右方向：24px', value: 'rounded-r-3xl' },
  { caption: '右方向：full', value: 'rounded-r-full' },
  { caption: '下方向：なし', value: 'rounded-b-none' },
  { caption: '下方向：2px', value: 'rounded-b-sm' },
  { caption: '下方向：4px', value: 'rounded-b' },
  { caption: '下方向：6px', value: 'rounded-b-md' },
  { caption: '下方向：8px', value: 'rounded-b-lg' },
  { caption: '下方向：12px', value: 'rounded-b-xl' },
  { caption: '下方向：16px', value: 'rounded-b-2xl' },
  { caption: '下方向：24px', value: 'rounded-b-3xl' },
  { caption: '下方向：full', value: 'rounded-b-full' },
  { caption: '左方向：なし', value: 'rounded-l-none' },
  { caption: '左方向：2px', value: 'rounded-l-sm' },
  { caption: '左方向：4px', value: 'rounded-l' },
  { caption: '左方向：6px', value: 'rounded-l-md' },
  { caption: '左方向：8px', value: 'rounded-l-lg' },
  { caption: '左方向：12px', value: 'rounded-l-xl' },
  { caption: '左方向：16px', value: 'rounded-l-2xl' },
  { caption: '左方向：24px', value: 'rounded-l-3xl' },
  { caption: '左方向：full', value: 'rounded-l-full' },
  { caption: '上左方向：なし', value: 'rounded-tl-none' },
  { caption: '上左方向：2px', value: 'rounded-tl-sm' },
  { caption: '上左方向：4px', value: 'rounded-tl' },
  { caption: '上左方向：6px', value: 'rounded-tl-md' },
  { caption: '上左方向：8px', value: 'rounded-tl-lg' },
  { caption: '上左方向：12px', value: 'rounded-tl-xl' },
  { caption: '上左方向：16px', value: 'rounded-tl-2xl' },
  { caption: '上左方向：24px', value: 'rounded-tl-3xl' },
  { caption: '上左方向：full', value: 'rounded-tl-full' },
  { caption: '上右方向：なし', value: 'rounded-tr-none' },
  { caption: '上右方向：2px', value: 'rounded-tr-sm' },
  { caption: '上右方向：4px', value: 'rounded-tr' },
  { caption: '上右方向：6px', value: 'rounded-tr-md' },
  { caption: '上右方向：8px', value: 'rounded-tr-lg' },
  { caption: '上右方向：12px', value: 'rounded-tr-xl' },
  { caption: '上右方向：16px', value: 'rounded-tr-2xl' },
  { caption: '上右方向：24px', value: 'rounded-tr-3xl' },
  { caption: '上右方向：full', value: 'rounded-tr-full' },
  { caption: '下右方向：なし', value: 'rounded-br-none' },
  { caption: '下右方向：2px', value: 'rounded-br-sm' },
  { caption: '下右方向：4px', value: 'rounded-br' },
  { caption: '下右方向：6px', value: 'rounded-br-md' },
  { caption: '下右方向：8px', value: 'rounded-br-lg' },
  { caption: '下右方向：12px', value: 'rounded-br-xl' },
  { caption: '下右方向：16px', value: 'rounded-br-2xl' },
  { caption: '下右方向：24px', value: 'rounded-br-3xl' },
  { caption: '下右方向：full', value: 'rounded-br-full' },
  { caption: '下左方向：なし', value: 'rounded-bl-none' },
  { caption: '下左方向：2px', value: 'rounded-bl-sm' },
  { caption: '下左方向：4px', value: 'rounded-bl' },
  { caption: '下左方向：6px', value: 'rounded-bl-md' },
  { caption: '下左方向：8px', value: 'rounded-bl-lg' },
  { caption: '下左方向：12px', value: 'rounded-bl-xl' },
  { caption: '下左方向：16px', value: 'rounded-bl-2xl' },
  { caption: '下左方向：24px', value: 'rounded-bl-3xl' },
  { caption: '下左方向：full', value: 'rounded-bl-full' },
]

export const fontSizeArrays = [
  { caption: 'xs', value: 'text-xs' },
  { caption: 'sm', value: 'text-sm' },
  { caption: 'base', value: 'text-base' },
  { caption: 'lg', value: 'text-lg' },
  { caption: 'xl', value: 'text-xl' },
  { caption: '2xl', value: 'text-2xl' },
  { caption: '3xl', value: 'text-3xl' },
  { caption: '4xl', value: 'text-4xl' },
  { caption: '5xl', value: 'text-5xl' },
  { caption: '6xl', value: 'text-6xl' },
  { caption: '7xl', value: 'text-7xl' },
  { caption: '8xl', value: 'text-8xl' },
  { caption: '9xl', value: 'text-9xl' },
]

export const fontWeightArrays = [
  { caption: '100', value: 'font-thin' },
  { caption: '200', value: 'font-extralight' },
  { caption: '300', value: 'font-light' },
  { caption: '400', value: 'font-normal' },
  { caption: '500', value: 'font-medium' },
  { caption: '600', value: 'font-semibold' },
  { caption: '700', value: 'font-bold' },
  { caption: '800', value: 'font-extrabold' },
  { caption: '900', value: 'font-black' },
]

export const borderWidthArrays = [
  { caption: '上右下左:なし', value: 'border-0' },
  { caption: '上右下左:1', value: 'border' },
  { caption: '上右下左:2', value: 'border-2' },
  { caption: '上右下左:4', value: 'border-4' },
  { caption: '上右下左:8', value: 'border-8' },
  { caption: '左右：なし', value: 'border-x-0' },
  { caption: '左右：1', value: 'border-x' },
  { caption: '左右：2', value: 'border-x-2' },
  { caption: '左右：4', value: 'border-x-4' },
  { caption: '左右：8', value: 'border-x-8' },
  { caption: '上下：なし', value: 'border-y-0' },
  { caption: '上下：1', value: 'border-y' },
  { caption: '上下：2', value: 'border-y-2' },
  { caption: '上下：4', value: 'border-y-4' },
  { caption: '上下：8', value: 'border-y-8' },
  { caption: '上：なし', value: 'border-t-0' },
  { caption: '上：1', value: 'border-t' },
  { caption: '上：2', value: 'border-t-2' },
  { caption: '上：4', value: 'border-t-4' },
  { caption: '上：8', value: 'border-t-8' },
  { caption: '右：なし', value: 'border-r-0' },
  { caption: '右：1', value: 'border-r' },
  { caption: '右：2', value: 'border-r-2' },
  { caption: '右：4', value: 'border-r-4' },
  { caption: '右：8', value: 'border-r-8' },
  { caption: '下：なし', value: 'border-b-0' },
  { caption: '下：1', value: 'border-b' },
  { caption: '下：2', value: 'border-b-2' },
  { caption: '下：4', value: 'border-b-4' },
  { caption: '下：8', value: 'border-b-8' },
  { caption: '左：なし', value: 'border-l-0' },
  { caption: '左：1', value: 'border-l' },
  { caption: '左：2', value: 'border-l-2' },
  { caption: '左：4', value: 'border-l-4' },
  { caption: '左：8', value: 'border-l-8' },
]

export const ringWidthFocusArrays = [
  { caption: 'なし', value: 'undefined' },
  { caption: '0px', value: 'ring-0' },
  { caption: '1px', value: 'ring-1' },
  { caption: '2px', value: 'ring-2' },
  { caption: '3px', value: 'ring' },
  { caption: '4px', value: 'ring-4' },
  { caption: '8px', value: 'ring-8' },
  { caption: 'inset', value: 'ring-inset' },
]

export const ringOffsetWidthFocusArrays = [
  { caption: 'なし', value: 'undefined' },
  { caption: '0px', value: 'ring-offset-0' },
  { caption: '1px', value: 'ring-offset-1' },
  { caption: '2px', value: 'ring-offset-2' },
  { caption: '4px', value: 'ring-offset-4' },
  { caption: '8px', value: 'ring-offset-8' },
]

export const ringWidthActiveArrays = [
  { caption: 'なし', value: 'undefined' },
  { caption: '0px', value: 'ring-0' },
  { caption: '1px', value: 'ring-1' },
  { caption: '2px', value: 'ring-2' },
  { caption: '3px', value: 'ring' },
  { caption: '4px', value: 'ring-4' },
  { caption: '8px', value: 'ring-8' },
  { caption: 'inset', value: 'ring-inset' },
]

export const ringOffsetWidthActiveArrays = [
  { caption: 'なし', value: 'undefined' },
  { caption: '0px', value: 'ring-offset-0' },
  { caption: '1px', value: 'ring-offset-1' },
  { caption: '2px', value: 'ring-offset-2' },
  { caption: '4px', value: 'ring-offset-4' },
  { caption: '8px', value: 'ring-offset-8' },
]

export const boxShadowArrays = [
  { caption: '小', value: 'shadow-sm' },
  { caption: '普通', value: 'shadow' },
  { caption: '中', value: 'shadow-md' },
  { caption: '大', value: 'shadow-lg' },
  { caption: '特大', value: 'shadow-xl' },
  { caption: '超特大', value: 'shadow-2xl' },
  { caption: '内側', value: 'shadow-inner' },
  { caption: 'なし', value: 'shadow-none' },
]

export const pageBlockTypes = [
  { blockPageId: '', key: '', blockPageTitle: 'ブロック追加' },
  { blockPageId: 1, key: 'BUTTON', blockPageTitle: 'ボタンブロック' },
  { blockPageId: 2, key: 'INFORMATION_AREA', blockPageTitle: '情報エリア' },
  { blockPageId: 3, key: 'IMAGE', blockPageTitle: '画像' },
  { blockPageId: 4, key: 'TEXT_LINK', blockPageTitle: 'テキストリンク' },
  { blockPageId: 5, key: 'H1', blockPageTitle: 'H1' },
  { blockPageId: 6, key: 'H2', blockPageTitle: 'H2' },
  { blockPageId: 7, key: 'H3', blockPageTitle: 'H3' },
  { blockPageId: 8, key: 'H4', blockPageTitle: 'H4' },
  { blockPageId: 9, key: 'H5', blockPageTitle: 'H5' },
  { blockPageId: 10, key: 'H6', blockPageTitle: 'H6' },
  { blockPageId: 11, key: 'PAGE_TITLE_SETTINGS_BLOCK', blockPageTitle: 'ページタイトル' },
  //{ blockPageId: 12, key: 'RESERVATION_NUMBER', blockPageTitle: '予約番号' },
  { blockPageId: 13, key: 'HORIZONTAL_LINE', blockPageTitle: '水平線' },
  { blockPageId: 14, key: 'SPACE_SETTINGS_BLOCK', blockPageTitle: 'スペーサー' },
  { blockPageId: 15, key: 'MAP', blockPageTitle: '地図ブロック' },
  { blockPageId: 16, key: 'HTML_EDITOR', blockPageTitle: 'WYSIWIG' },
  //{ blockPageId: 17, key: 'JOIN_INPUT_FORM_SETTINGS_BLOCK', blockPageTitle: '[江別]結合入力' },
  //{ blockPageId: 18, key: 'COMBINE_INPUT_TEXT', blockPageTitle: '結合入力フォーム' },
  //{ blockPageId: 19, key: 'INPUT_TEXT_SETTINGS_BLOCK', blockPageTitle: '[江別]入力' },
  { blockPageId: 20, key: 'INPUT_TEXT', blockPageTitle: '入力フォームinputText' },
  { blockPageId: 21, key: 'INPUT_DATE_SETTINGS_BLOCK', blockPageTitle: '入力フォームinputDate' },
  //{ blockPageId: 22, key: 'BIRTHDAY_SETTINGS_BLOCK', blockPageTitle: '[江別]誕生日' },
  { blockPageId: 23, key: 'INPUT_BIRTHDAY', blockPageTitle: '入力フォームinputBirthDay' },
  { blockPageId: 24, key: 'INPUT_TIME_SETTINGS_BLOCK', blockPageTitle: '入力フォームinputTime' },
  { blockPageId: 25, key: 'INPUT_NUMBER_SETTINGS_BLOCK', blockPageTitle: '入力フォームinputNumber' },
  { blockPageId: 26, key: 'INPUT_TEXTAREA_SETTINGS_BLOCK', blockPageTitle: '入力フォームinputTextArea' },
  { blockPageId: 27, key: 'CHECKBOX_SETTINGS_BLOCK', blockPageTitle: '入力フォームcheckbox' },
  //{ blockPageId: 28, key: 'SELECT_SETTINGS_BLOCK', blockPageTitle: '[江別]select' },
  { blockPageId: 29, key: 'OPTION_SELECT', blockPageTitle: '入力フォームselect' },
  //{ blockPageId: 30, key: 'RADIOA_SETTINGS_BLOCK', blockPageTitle: '[江別]radio' },
  { blockPageId: 31, key: 'RADIO_A', blockPageTitle: '入力フォームinputRadioA' },
  { blockPageId: 32, key: 'RADIOB_SETTINGS_BLOCK', blockPageTitle: '入力フォームinputRadioB' },
  //{ blockPageId: 33, key: 'FIELD_DISPLAY_SETTINGS_BLOCK', blockPageTitle: '[江別]フィールド' },
  { blockPageId: 34, key: 'DISPLAY_FIELD', blockPageTitle: 'フィールド表示' },
  //{ blockPageId: 35, key: 'ZIP_CODE_SEARCH_SETTINGS_BLOCK', blockPageTitle: '[江別]郵便番号' },
  { blockPageId: 36, key: 'ZIP_CODE_SEARCH', blockPageTitle: '郵便番号検索' },
  //{ blockPageId: 37, key: 'CATEGORY_SETTINGS_BLOCK', blockPageTitle: '[江別]カテゴリー' },
  { blockPageId: 38, key: 'CATEGORY', blockPageTitle: 'カテゴリー' },
  //{ blockPageId: 39, key: 'BUS_SETTINGS_BLOCK', blockPageTitle: '[江別]バス' },
  { blockPageId: 40, key: 'SLOT', blockPageTitle: 'スロット' },
  //{ blockPageId: 41, key: 'ITEM_SETTINGS_BLOCK', blockPageTitle: '[江別]アイテム' },
  { blockPageId: 42, key: 'ITEM', blockPageTitle: 'アイテム' },
  { blockPageId: 43, key: 'INSTITUTE', blockPageTitle: '施設' },
  //{ blockPageId: 44, key: 'TERMSS_OF_SERVICE', blockPageTitle: '[江別]利用規約' },
  { blockPageId: 45, key: 'TERMS_OF_SERVICE', blockPageTitle: '利用規約' },
  //{ blockPageId: 46, key: 'LOGIN_BUTTON', blockPageTitle: '[江別]予約' },
  { blockPageId: 47, key: 'ONE_BUTTON_LOGIN', blockPageTitle: 'ワンボタンログイン' },
  { blockPageId: 48, key: 'ONE_TOKEN_LOGIN_BLOCK', blockPageTitle: '1トークンログイン' },
  //{ blockPageId: 49, key: 'TWO_TOKEN_LOGIN_BLOCK', blockPageTitle: '[江別]変更' },
  // { blockPageId: 50, key: 'TWO_TOKEN_LOGIN', blockPageTitle: '2トークンログイン' }, //this option not needed
  { blockPageId: 51, key: 'TWO_TOKEN_LOGIN_1', blockPageTitle: '誕生日ログイン' },
  { blockPageId: 52, key: 'TWO_TOKEN_LOGIN_2', blockPageTitle: 'テキストログイン' },
  { blockPageId: 53, key: 'THREE_TOKEN_LOGIN', blockPageTitle: '3トークンログイン' },
  { blockPageId: 54, key: 'DISPLAY_CONTROL_BLOCK_SETTING', blockPageTitle: '表示制御ブロック設定' },

  { blockPageId: 59, key: 'displayItem', blockPageTitle: 'フィールドアイテム' },
]

export const linkTypes = [
  { id: 1, caption: 'URL', value: 'url_self' },
  { id: 2, caption: 'URL 別タブ', value: 'url_blank' },
  { id: 3, caption: 'MAIL', value: 'mail' },
  { id: 4, caption: 'TEL', value: 'tel' },
  { id: 5, caption: 'SMS', value: 'sms' },
]
export const reservationSlotsDummyData = {
  "facility": "足立区生涯学習センター",
  "date": "2022年9月13日（木）",
  "slots": [
    { "time": "9:30", "numberOfRemaining": 3 },
    { "time": "9:45", "numberOfRemaining": 0 },
    { "time": "10:00", "numberOfRemaining": 2 },
    { "time": "10:15", "numberOfRemaining": 5 },
    { "time": "10:30", "numberOfRemaining": 0 },
    { "time": "10:45", "numberOfRemaining": 1 },
    { "time": "11:00", "numberOfRemaining": 10 },
    { "time": "11:15", "numberOfRemaining": 0 },
    { "time": "11:30", "numberOfRemaining": 1 },
    { "time": "11:45", "numberOfRemaining": 3 },
    { "time": "13:15", "numberOfRemaining": 0 },
    { "time": "13:30", "numberOfRemaining": 2 },
    { "time": "13:45", "numberOfRemaining": 0 },
    { "time": "14:00", "numberOfRemaining": 0 },
    { "time": "14:15", "numberOfRemaining": 0 },
    { "time": "14:30", "numberOfRemaining": 0 },
    { "time": "14:45", "numberOfRemaining": 6 },
    { "time": "15:00", "numberOfRemaining": 0 },
    { "time": "15:15", "numberOfRemaining": 4 },
    { "time": "15:30", "numberOfRemaining": 3 },
    { "time": "15:45", "numberOfRemaining": 3 },
    { "time": "16:00", "numberOfRemaining": 5 },
    { "time": "16:15", "numberOfRemaining": 0 },
    { "time": "16:30", "numberOfRemaining": 10 },
    { "time": "16:45", "numberOfRemaining": 0 }
  ]
};
export const numOfMaxLength = {
  0: 0,
  1: 10,
  2: 100,
  3: 1000,
  4: 10000,
  5: 100000,
  6: 1000000,
  7: 10000000,
  8: 100000000,
  9: 1000000000,
}


export const defaultCommonPages = [
  { appCommonPageId: '', appCommonPageSubId: 0, appId: 0, appCommonPageTitle: '404', appCommonPageManagerName: '404', appCommonPageURLName: '404', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 1, appId: 0, appCommonPageTitle: '401', appCommonPageManagerName: '401', appCommonPageURLName: '401', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 2, appId: 0, appCommonPageTitle: '403', appCommonPageManagerName: '403', appCommonPageURLName: '403', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 3, appId: 0, appCommonPageTitle: '500', appCommonPageManagerName: '500', appCommonPageURLName: '500', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 4, appId: 0, appCommonPageTitle: 'イベント期間外', appCommonPageManagerName: 'イベント期間外', appCommonPageURLName: 'event_over', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 5, appId: 0, appCommonPageTitle: '不正遷移エラー', appCommonPageManagerName: '不正遷移エラー', appCommonPageURLName: 'transition_error', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 6, appId: 0, appCommonPageTitle: 'メンテナンス中', appCommonPageManagerName: 'メンテナンス中', appCommonPageURLName: 'under_maintenance', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 7, appId: 0, appCommonPageTitle: 'システムエラー', appCommonPageManagerName: 'システムエラー', appCommonPageURLName: 'system_error', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 8, appId: 0, appCommonPageTitle: 'デバイスエラー', appCommonPageManagerName: 'デバイスエラー', appCommonPageURLName: 'device_error', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
  { appCommonPageId: '', appCommonPageSubId: 9, appId: 0, appCommonPageTitle: 'その他エラー', appCommonPageManagerName: 'その他エラー', appCommonPageURLName: 'unknown_error', appCommonPageDescription: '', appCommonPageCustomClass: '', blocks: [], updatedBy: '', isNewPage: true },
]

export const readOnlyDropDownItems = [
  { caption: '書き込み可', value: false },
  { caption: '書き込み不可', value: true },
];

export const requiredDropDownItems = [
  { caption: '任意', value: false },
  { caption: '必須', value: true },
];

export const displayDateFormatList = [
  { caption: 'ゼロ埋めあり:YYYY年(EEYY年)MM月DD日', value: '0' },
  { caption: 'ゼロ埋めあり:YYYY(EEYY)/MM/DD', value: '1' },
  { caption: 'ゼロ埋めあり:YYYY(EEYY)-MM-DD', value: '2' },
  { caption: 'ゼロ埋めあり:YYYY年MM月DD日', value: '3' },
  { caption: 'ゼロ埋めあり:YYYY/MM/DD', value: '4' },
  { caption: 'ゼロ埋めあり:YYYY-MM-DD', value: '5' },
  { caption: 'ゼロ埋めあり:YYYYMMDD日', value: '6' },
  { caption: 'ゼロ埋めなし:YYYY年(EEYY年)MM月DD日', value: '7' },
  { caption: 'ゼロ埋めなし:YYYY(EEYY)/MM/DD', value: '8' },
  { caption: 'ゼロ埋めなし:YYYY(EEYY)-MM-DD', value: '9' },
  { caption: 'ゼロ埋めなし:YYYY年MM月DD日', value: '10' },
  { caption: 'ゼロ埋めなし:YYYY/MM/DD', value: '11' },
  { caption: 'ゼロ埋めなし:YYYY-MM-DD', value: '12' },
]

export const pickerDropDownList = [
  { caption: '使用しない', value: '0' },
  { caption: 'ブラウザーピッカー', value: '1' },
  // { caption: 'ピッカー1', value: '2' },
  // { caption: 'ピッカー2', value: '3' },
]

export const divisionDropDrownList = [
  { caption: '分割しない', value: false },
  { caption: '年月日に分割する', value: true },
]

export const yearTypeDropDownList = [
  { caption: 'YYYY年(EEYY年)', value: '0' },
  { caption: '年月日に分割する', value: '1' },
]

export const monthDayTypeDropDownList = [
  { caption: 'ドロップダウン', value: '0' },
  { caption: 'ブラウザーピッカー', value: '1' },
]

export const displayTimeFormatList = [
  { caption: 'ゼロ埋めあり:HH:MM', value: '0' },
  { caption: 'ゼロ埋めあり:HH時MM分', value: '1' },
  { caption: 'ゼロ埋めあり:HH-MM', value: '2' },
  { caption: 'ゼロ埋めあり:HHMM', value: '3' },
  { caption: 'ゼロ埋めなし:HH:MM', value: '4' },
  { caption: 'ゼロ埋めなし:HH時MM分', value: '5' },
  { caption: 'ゼロ埋めなし:HH-MM', value: '6' },
]

export const hourTypeList = [
  { caption: 'ゼロ埋めあり:HH', value: '0' },
  { caption: 'ゼロ埋めあり:HH時', value: '1' },
  { caption: 'ゼロ埋めなし:HH', value: '2' },
  { caption: 'ゼロ埋めなし:HH時', value: '3' },
]

export const minuteTypeList = [
  { caption: 'ゼロ埋めあり:MM', value: '0' },
  { caption: 'ゼロ埋めあり:MM分', value: '1' },
  { caption: 'ゼロ埋めなし:MM', value: '2' },
  { caption: 'ゼロ埋めなし:MM分', value: '3' },
]

export const inputModes = [
  { caption: '指定しない', value: 'none' },
  { caption: 'テキスト', value: 'text' },
  { caption: '電話番号', value: 'tel' },
  { caption: 'URL', value: 'url' },
  { caption: 'Eメールアドレス', value: 'email' },
  { caption: '数値入力', value: 'numeric' },
  { caption: '整数値入力', value: 'decimal' },
  { caption: '検索語入力モード', value: 'search' },
  { caption: 'ラテン文字逐語モード', value: 'verbatim' },
  { caption: 'ラテン文字モード', value: 'latin' },
  { caption: 'ラテン文字入力モード(名前入力用)', value: 'latin-name' },
  { caption: 'ラテン文字文章入力モード', value: 'latin-prose' },
  { caption: '全角ラテン文字入力モード', value: 'full-width-latin' },
  { caption: '漢字変換ひらがな入力モード', value: 'kana' },
  { caption: '漢字変換ひらがな入力モード(名前入力用)', value: 'kana-name' },
  { caption: 'カタカナ入力モード', value: 'katakana' },
]

export const inputTypes = [
  { caption: 'テキスト入力欄 （初期値）', value: 'text' },
  { caption: 'パスワード入力欄', value: 'password' },
  { caption: '電話番号', value: 'tel' },
  { caption: 'URL', value: 'url' },
  { caption: 'メールアドレス', value: 'email' },
  // { caption: '日時(UTC)', value: 'datetime' },
  { caption: '日時(ローカル)', value: 'datetime-local' },
  { caption: '日付', value: 'date' },
  { caption: '月', value: 'month' },
  { caption: '週', value: 'week' },
  { caption: '時間', value: 'time' },
  { caption: '数値', value: 'number' },

]

export const formType6DropDownItems = [
  { caption: 'そのまま表示（0埋めあり）', value: 1 },
  { caption: 'そのまま表示（0埋めなし）', value: 2 },
  { caption: '〇〇時〇〇分（0埋めあり）', value: 3 },
  { caption: '〇〇時〇〇分（0埋めなし）', value: 4 },
  { caption: '午前〇〇時〇〇分（0埋めあり）', value: 5 },
  { caption: '午前〇〇時〇〇分（0埋めなし）', value: 6 },
  { caption: '〇〇:〇〇（0埋めあり）', value: 7 },
  { caption: '〇〇:〇〇（0埋めなし）', value: 8 },
]

export const formType7DropDownItems = [
  { caption: 'そのまま表示（123456）', value: '1' },
  { caption: '123,456', value: '2' },
  { caption: '123,456円', value: '3' },
  { caption: '¥123,456', value: '4' },
]


export const strokeSizeArray = [
  { value: 'stroke-[0px]', caption: '0px' },
  { value: 'stroke-[1px]', caption: '1px' },
  { value: 'stroke-[2px]', caption: '2px' },
  { value: 'stroke-[3px]', caption: '3px' },
  { value: 'stroke-[4px]', caption: '4px' },
]


export const iconList = [
  { id: 1, caption: 'Ant Design Icons', value: 'antDesignIcons' },
  { id: 2, caption: 'Bootstrap Icons', value: 'bootstrapIcons' },
  { id: 3, caption: 'BoxIcons', value: 'boxIcons' },
  { id: 4, caption: 'Circum Icons', value: 'circumIcons' },
  { id: 5, caption: 'Devicons', value: 'devicons' },
  { id: 6, caption: 'Feather', value: 'feather' },
  // { id: 7, caption: 'Flat Color Icons', value: 'flatColorIcons' },
  { id: 8, caption: 'Font Awesome', value: 'fontAwesome' },
  { id: 9, caption: 'Github Octicons icons', value: 'githubOcticonsIcons' },
  { id: 10, caption: 'Grommet-Icons', value: 'grommetIcons' },
  { id: 11, caption: 'Heroicons', value: 'heroicons' },
  { id: 12, caption: 'Heroicons2', value: 'heroicons2' },
  { id: 13, caption: 'IcoMoon Free', value: 'icoMoonFree' },
  { id: 14, caption: 'Ionicons 4', value: 'ionicons4' },
  { id: 15, caption: 'Ionicons 5', value: 'ionicons5' },
  { id: 16, caption: 'Material Design icons', value: 'materialDesignIcons' },
  { id: 17, caption: 'Radix Icons', value: 'radixIcons' },
  { id: 18, caption: 'Remix Icon', value: 'remixIcon' },
  { id: 19, caption: 'Simple Icons', value: 'simpleIcons' },
  { id: 20, caption: 'Simple Line Icons', value: 'simpleLineIcons' },
  { id: 21, caption: 'Tabler Icons', value: 'tablerIcons' },
  { id: 22, caption: 'Themify Icons', value: 'themifyIcons' },
  { id: 23, caption: 'Typicons', value: 'typicons' },
  { id: 24, caption: 'VS Code Icons', value: 'vSCodeIcons' },
  { id: 25, caption: 'Weather Icons', value: 'weatherIcons' },
  { id: 26, caption: 'css.gg', value: 'cssIcon' },
]

export const buttonFunction = [
  { caption: '画面遷移(スピナーは表示されません)', value: 'onClick' },
  { caption: '電話発信(スピナーは表示されません)', value: 'outgoingCall' },
  { caption: 'メール送信(スピナーは表示されません)', value: 'sendEmail' },
  { caption: '予約実行', value: 'reservation' },
  { caption: '予約取消', value: 'reservationCancel' },
  { caption: '予約変更', value: 'reservationChange' },
  { caption: '外部リンク(スピナーは表示されません)', value: 'externalLink' },
  { caption: 'フィールド送信', value: 'sendField' },
  { caption: '何もしない(スピナーは表示されません)', value: 'doNothing' },
]

export const buttonValidationKeys = [
  'JOIN_INPUT_FORM_SETTINGS_BLOCK',
  'COMBINE_INPUT_TEXT',
  'INPUT_TEXT_SETTINGS_BLOCK',
  'INPUT_TEXT',
  'INPUT_DATE_SETTINGS_BLOCK',
  'BIRTHDAY_SETTINGS_BLOCK',
  'INPUT_BIRTHDAY',
  'INPUT_TIME_SETTINGS_BLOCK',
  'INPUT_NUMBER_SETTINGS_BLOCK',
  'INPUT_TEXTAREA_SETTINGS_BLOCK',
  'CHECKBOX_SETTINGS_BLOCK',
  'SELECT_SETTINGS_BLOCK',
  'OPTION_SELECT',
  'RADIOA_SETTINGS_BLOCK',
  'RADIO_A',
  'RADIOB_SETTINGS_BLOCK',
  'ZIP_CODE_SEARCH_SETTINGS_BLOCK',
  'ZIP_CODE_SEARCH',
  'TWO_TOKEN_LOGIN',
  'TWO_TOKEN_LOGIN_1',
  'TWO_TOKEN_LOGIN_2',
  // 'TERMSS_OF_SERVICE',
  // 'TERMS_OF_SERVICE',
  // 'ITEM',
  // 'INSTITUTE',
  // 'CATEGORY_SETTINGS_BLOCK',
  // 'CATEGORY',
  // 'BUS_SETTINGS_BLOCK',
  // 'SLOT',
  // 'ITEM_SETTINGS_BLOCK',
];

export const fieldNameValidateKeys = [
  'name',
  'area1Name',
  'area2Name',
  'area3Name',
  'area4Name',
  'area5Name',
  'yearName',
  'monthName',
  'dayName',
  'hourName',
  'minuteName',
  'input1Name',
  'input2Name',
  'input3Name',
  'input4Name',
  'input5Name',
  'input6Name',
  't1Area1Name',
  't1Area2Name',
  't1Area3Name',
  't1Area4Name',
  'id1Name',
  'id2Name',
  'id3Name',
  'id4Name',
  'passwordName'
];
