export const slotData = {
    data: [
        {
            head: [
                { dayOfWeekNumber: '99', dateName: '受付時間' },
                { dayOfWeekNumber: 0, dateName: '4/2 (日)' },
                { dayOfWeekNumber: 1, dateName: '4/3 (月)' },
                { dayOfWeekNumber: 2, dateName: '4/4 (火)' },
                { dayOfWeekNumber: 3, dateName: '4/5 (水)' },
                { dayOfWeekNumber: 4, dateName: '4/6 (木)' },
                { dayOfWeekNumber: 5, dateName: '4/7 (金)' },
                { dayOfWeekNumber: 6, dateName: '4/8 (土)' },
            ],
            slotTime: ['09:30', '10:00', '10:30', '11:00', 1030, 1100, 1300, 1330],
            slot: [
                [
                    { slotType: 'datetime', slotValue: '09:30' },
                    { dateTime: '4/2 (日)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/3 (月)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/4 (火)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: '10:00' },
                    { dateTime: '4/2 (日)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/3 (月)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/4 (火)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: '10:30' },
                    { dateTime: '4/2 (日)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/3 (月)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/4 (火)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: '11:00' },
                    { dateTime: '4/2 (日)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/3 (月)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/4 (火)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
            ],
            institute: [],
        },
        {
            head: [
                { dayOfWeekNumber: '99', dateName: '受付時間' },
                { dayOfWeekNumber: 0, dateName: 1670727600 },
                { dayOfWeekNumber: 1, dateName: 1670814000 },
                { dayOfWeekNumber: 2, dateName: 1670900400 },
                { dayOfWeekNumber: 3, dateName: 1670986800 },
                { dayOfWeekNumber: 4, dateName: 1671073200 },
                { dayOfWeekNumber: 5, dateName: 1671159600 },
                { dayOfWeekNumber: 6, dateName: 1671246000 },
            ],
            slotTime: [830, 900, 930, 1000, 1030, 1100, 1300, 1330],
            slot: [
                [
                    { slotType: 'datetime', slotValue: 830 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 900 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 930 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1000 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1030 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1100 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1300 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1330 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
            ],
            institute: [],
        },
    ],
};

export const slot2Data = [
    {
        categoryName: 'はつらつ検診',
        eventInstituteId: 1255,
        instituteName: 'セシオン杉並',
        instituteZipCode: '067-0004',
        institutePrefecture: '北海道',
        instituteCityName: '江別市',
        instituteTownName: '若草町',
        instituteAddressName: '６−１',
        instituteBuilding: '',
        instituteTelNo: '011-385-5252',
        instituteImageURL1: '',
        instituteImageURL2: '',
        instituteImageURL3: '',
        mappingDatetime: 1661655600,
        mappingId: 5190,
        slots: [
            { slotId: 264129, datetime: 630, maxReservationCount: 21, reservationCount: 1 },
            { slotId: 264143, datetime: 700, maxReservationCount: 21, reservationCount: 0 },
            { slotId: 264157, datetime: 730, maxReservationCount: 21, reservationCount: 0 },
            { slotId: 264171, datetime: 800, maxReservationCount: 21, reservationCount: 0 },
            { slotId: 264185, datetime: 830, maxReservationCount: 21, reservationCount: 0 },
        ],
    },
    {
        categoryName: 'はつらつ検診',
        eventInstituteId: 1255,
        instituteName: 'セシオン杉並',
        instituteZipCode: '067-0004',
        institutePrefecture: '北海道',
        instituteCityName: '江別市',
        instituteTownName: '若草町',
        instituteAddressName: '６−１',
        instituteBuilding: '',
        instituteTelNo: '011-385-5252',
        instituteImageURL1: '',
        instituteImageURL2: '',
        instituteImageURL3: '',
        mappingDatetime: 1661742000,
        mappingId: 5191,
        slots: [
            { slotId: 264269, datetime: 630, maxReservationCount: 21, reservationCount: 0 },
            { slotId: 264283, datetime: 700, maxReservationCount: 21, reservationCount: 0 },
            { slotId: 264297, datetime: 730, maxReservationCount: 21, reservationCount: 0 },
            { slotId: 264311, datetime: 800, maxReservationCount: 21, reservationCount: 0 },
            { slotId: 264325, datetime: 830, maxReservationCount: 21, reservationCount: 0 },
        ],
    },
];

export const deliveryData = {
    data: [
        {
            head: [
                { dayOfWeekNumber: '99', dateName: '受付時間' },
                { dayOfWeekNumber: 0, dateName: '4/2 (日)' },
                { dayOfWeekNumber: 1, dateName: '4/3 (月)' },
                { dayOfWeekNumber: 2, dateName: '4/4 (火)' },
                { dayOfWeekNumber: 3, dateName: '4/5 (水)' },
                { dayOfWeekNumber: 4, dateName: '4/6 (木)' },
                { dayOfWeekNumber: 5, dateName: '4/7 (金)' },
                { dayOfWeekNumber: 6, dateName: '4/8 (土)' },
            ],
            slotTime: ['09:30', '10:00', '10:30', '11:00', 1030, 1100, 1300, 1330],
            slot: [
                [
                    { slotType: 'datetime', slotValue: '09:30' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { dateTime: '4/5 (水)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/6 (木)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/7 (金)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: '10:00' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { dateTime: '4/5 (水)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/6 (木)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/7 (金)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: '10:30' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { dateTime: '4/5 (水)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/6 (木)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/7 (金)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: '11:00' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { dateTime: '4/2 (日)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/3 (月)', maxReservationCount: 20, reservationCount: 0 },
                    { dateTime: '4/4 (火)', maxReservationCount: 20, reservationCount: 0 },
                    { slotType: 'empty' },
                ],
            ],
            institute: [
                { instituteNumber: 'title', instituteName: '検診場所' },
                { instituteNumber: 0, instituteName: '' },
                { instituteNumber: 0, instituteName: '' },
                { instituteNumber: 256, instituteName: '' },
                { instituteNumber: 256, instituteName: '区画整理記念会館（江別市朝日町１１−１２）' },
                { instituteNumber: 256, instituteName: '野幌鉄南地区センター（江別市東野幌本町６２−１）' },
                { instituteNumber: 0, instituteName: '野幌公民館（江別市野幌町１３−６）' },
                { instituteNumber: 0, instituteName: '' },
            ],
        },
        {
            head: [
                { dayOfWeekNumber: '99', dateName: '受付時間' },
                { dayOfWeekNumber: 0, dateName: 1670727600 },
                { dayOfWeekNumber: 1, dateName: 1670814000 },
                { dayOfWeekNumber: 2, dateName: 1670900400 },
                { dayOfWeekNumber: 3, dateName: 1670986800 },
                { dayOfWeekNumber: 4, dateName: 1671073200 },
                { dayOfWeekNumber: 5, dateName: 1671159600 },
                { dayOfWeekNumber: 6, dateName: 1671246000 },
            ],
            slotTime: [830, 900, 930, 1000, 1030, 1100, 1300, 1330],
            slot: [
                [
                    { slotType: 'datetime', slotValue: 830 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 900 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 930 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1000 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1030 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1100 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1300 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
                [
                    { slotType: 'datetime', slotValue: 1330 },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                    { slotType: 'empty' },
                ],
            ],
            institute: [],
        },
    ],
};

export const busData = [
    {
        slotId: 87980,
        mappingId: 1666,
        mappingDatetime: '03/08(水)',
        rowspanCount: 2,
        groupId: 1,
        datetime: 0,
        maxReservationCount: 50,
        reservationCount: 0,
        busWayId: 450,
        busWayName: '50名便',
        busWayCapacity: 50,
        busRouteName: '美唄バス路線',
        busRouteStopStyle: [
            {
                info2: '西3条南3丁目6-3',
                number: 752,
                Task_ID: 'dbf67fbf-e462-4e78-9243-0d5c5b9282e6',
                fTypeId: 239,
                inputBox: {
                    id: '5036f9cc-6ba9-468a-b76f-d884a140681b',
                    value: '保健センター',
                },
                checkbox1: {
                    id: 'f6d5300e-e1dc-4fea-8905-ebf15c5ea8c4',
                    type: 'checkbox',
                    checked: false,
                },
                checkbox2: {
                    id: '24f952fe-0b08-4b38-ad69-51bbcd62f1dc',
                    type: 'checkbox',
                    checked: false,
                },
                fieldData: '',
                inputBox2: {
                    id: 'c4942371-9b66-4452-94a9-6c47f4e5398d',
                    value: '保健センター',
                },
                currentPos: 0,
                expandType: 'F',
                Task_Subject: '251',
            },
            {
                info2: '自分の車で行く等',
                number: 341,
                Task_ID: '7b473e5d-2b0d-4dfc-9cdc-4fae98e81090',
                fTypeId: 238,
                inputBox: {
                    id: '71313da2-2f72-4dae-9afe-87b2d71166e2',
                    value: 'バスに乗らない',
                },
                checkbox1: {
                    id: 'e31a2aee-ac1e-4caa-83a6-57f49f7f9d8c',
                    type: 'checkbox',
                    checked: false,
                },
                checkbox2: {
                    id: 'ccb6e1a3-a8c6-4288-bc1d-696bccf31e11',
                    type: 'checkbox',
                    checked: false,
                },
                fieldData: '',
                inputBox2: {
                    id: '32b83eae-d05c-474c-a35e-1815524d6e05',
                    value: 'バスに乗らない',
                },
                currentPos: 1,
                expandType: 'F',
                Task_Subject: '101',
            },
        ],
        busStopName: 'バスに乗らない',
        busStopAddress: '自分の車で行く等',
        busTime: '08:00',
        eventBusId: 337,
    },
    {
        slotId: 87980,
        mappingId: 1666,
        mappingDatetime: '03/08(水)',
        rowspanCount: 0,
        groupId: 1,
        datetime: 0,
        maxReservationCount: 50,
        reservationCount: 0,
        busWayId: 450,
        busWayName: '50名便',
        busWayCapacity: 50,
        busRouteName: '美唄バス路線',
        busRouteStopStyle: [
            {
                info2: '西3条南3丁目6-3',
                number: 752,
                Task_ID: 'dbf67fbf-e462-4e78-9243-0d5c5b9282e6',
                fTypeId: 239,
                inputBox: {
                    id: '5036f9cc-6ba9-468a-b76f-d884a140681b',
                    value: '保健センター',
                },
                checkbox1: {
                    id: 'f6d5300e-e1dc-4fea-8905-ebf15c5ea8c4',
                    type: 'checkbox',
                    checked: false,
                },
                checkbox2: {
                    id: '24f952fe-0b08-4b38-ad69-51bbcd62f1dc',
                    type: 'checkbox',
                    checked: false,
                },
                fieldData: '',
                inputBox2: {
                    id: 'c4942371-9b66-4452-94a9-6c47f4e5398d',
                    value: '保健センター',
                },
                currentPos: 0,
                expandType: 'F',
                Task_Subject: '251',
            },
            {
                info2: '自分の車で行く等',
                number: 341,
                Task_ID: '7b473e5d-2b0d-4dfc-9cdc-4fae98e81090',
                fTypeId: 238,
                inputBox: {
                    id: '71313da2-2f72-4dae-9afe-87b2d71166e2',
                    value: 'バスに乗らない',
                },
                checkbox1: {
                    id: 'e31a2aee-ac1e-4caa-83a6-57f49f7f9d8c',
                    type: 'checkbox',
                    checked: false,
                },
                checkbox2: {
                    id: 'ccb6e1a3-a8c6-4288-bc1d-696bccf31e11',
                    type: 'checkbox',
                    checked: false,
                },
                fieldData: '',
                inputBox2: {
                    id: '32b83eae-d05c-474c-a35e-1815524d6e05',
                    value: 'バスに乗らない',
                },
                currentPos: 1,
                expandType: 'F',
                Task_Subject: '101',
            },
        ],
        busStopName: '保健センター',
        busStopAddress: '西3条南3丁目6-3',
        busTime: '08:25',
        eventBusId: 337,
    },
    {
        slotId: 88036,
        mappingId: 1667,
        mappingDatetime: '03/20(月)',
        rowspanCount: 2,
        groupId: 2,
        datetime: 0,
        maxReservationCount: 50,
        reservationCount: 0,
        busWayId: 450,
        busWayName: '50名便',
        busWayCapacity: 50,
        busRouteName: '美唄バス路線',
        busRouteStopStyle: [
            {
                info2: '西3条南3丁目6-3',
                number: 752,
                Task_ID: 'dbf67fbf-e462-4e78-9243-0d5c5b9282e6',
                fTypeId: 239,
                inputBox: {
                    id: '5036f9cc-6ba9-468a-b76f-d884a140681b',
                    value: '保健センター',
                },
                checkbox1: {
                    id: 'f6d5300e-e1dc-4fea-8905-ebf15c5ea8c4',
                    type: 'checkbox',
                    checked: false,
                },
                checkbox2: {
                    id: '24f952fe-0b08-4b38-ad69-51bbcd62f1dc',
                    type: 'checkbox',
                    checked: false,
                },
                fieldData: '',
                inputBox2: {
                    id: 'c4942371-9b66-4452-94a9-6c47f4e5398d',
                    value: '保健センター',
                },
                currentPos: 0,
                expandType: 'F',
                Task_Subject: '251',
            },
            {
                info2: '自分の車で行く等',
                number: 341,
                Task_ID: '7b473e5d-2b0d-4dfc-9cdc-4fae98e81090',
                fTypeId: 238,
                inputBox: {
                    id: '71313da2-2f72-4dae-9afe-87b2d71166e2',
                    value: 'バスに乗らない',
                },
                checkbox1: {
                    id: 'e31a2aee-ac1e-4caa-83a6-57f49f7f9d8c',
                    type: 'checkbox',
                    checked: false,
                },
                checkbox2: {
                    id: 'ccb6e1a3-a8c6-4288-bc1d-696bccf31e11',
                    type: 'checkbox',
                    checked: false,
                },
                fieldData: '',
                inputBox2: {
                    id: '32b83eae-d05c-474c-a35e-1815524d6e05',
                    value: 'バスに乗らない',
                },
                currentPos: 1,
                expandType: 'F',
                Task_Subject: '101',
            },
        ],
        busStopName: 'バスに乗らない',
        busStopAddress: '自分の車で行く等',
        busTime: '08:00',
        eventBusId: 338,
    },
];

export const itemData = [
    {
        slotId: 87981,
        itemId: 604,
        maxReservationCount: 50,
        reservationCount: 0,
        priority: 0,
        itemName: '胃がん検診（バリウム）',
        itemDescription: 'バリウムによる胃がん検診は、バリウムと発泡剤を飲み胃のX線撮影を行います。',
        itemOverview: '',
        filterId: 950,
        filterQuery: [['ab9022db', '=', true], 'and', ['9d374129', '=', true], 'and', ['eventage', '>=', 30]],
        eventSubItemId: 25122,
        required: 0,
        defaultSelected: 0,
        singleSelected: 0,
        parentItemId: 0,
        requiredItemId: [[]],
        prohibitionItemId: [
            [606, 629],
            [606, 628],
            [628, 612],
            [629, 612],
        ],
        chainItemId: ['604:1', '604:2'],
        itemSubId: 0,
        itemPrice: 500,
    },
    {
        slotId: 87984,
        itemId: 605,
        maxReservationCount: 50,
        reservationCount: 0,
        priority: 0,
        itemName: 'ピロリ菌検査',
        itemDescription: 'ピロリ菌検査は、採血による抗体検査を行います。胃がん検診を申し込んだ場合のみ受診できます。',
        itemOverview: '',
        filterId: 951,
        filterQuery: [['ab9022db', '=', true], 'and', ['9d374129', '=', true], 'and', ['eventage', '>=', 40]],
        eventSubItemId: 25125,
        required: 0,
        defaultSelected: 0,
        singleSelected: 0,
        parentItemId: 0,
        requiredItemId: [[]],
        prohibitionItemId: [
            [606, 629],
            [606, 628],
            [628, 612],
            [629, 612],
        ],
        chainItemId: ['605:1'],
        itemSubId: 0,
        itemPrice: 1000,
    },
    {
        slotId: 87986,
        itemId: 606,
        maxReservationCount: 50,
        reservationCount: 0,
        priority: 0,
        itemName: '肺がん検診',
        itemDescription: '肺がん検診は、胸部Ｘ線撮影を行います。',
        itemOverview: '',
        filterId: 950,
        filterQuery: [['ab9022db', '=', true], 'and', ['9d374129', '=', true], 'and', ['eventage', '>=', 30]],
        eventSubItemId: 25127,
        required: 0,
        defaultSelected: 0,
        singleSelected: 0,
        parentItemId: 0,
        requiredItemId: [[]],
        prohibitionItemId: [
            [606, 629],
            [606, 628],
            [628, 612],
            [629, 612],
        ],
        chainItemId: ['606:1', '606:2'],
        itemSubId: 0,
        itemPrice: 200,
    },
    {
        slotId: 87989,
        itemId: 629,
        maxReservationCount: 25,
        reservationCount: 0,
        priority: 0,
        itemName: '大腸がん検診',
        itemDescription: '大腸がん検診は、2日分の便で潜血検査を行います。',
        itemOverview: '',
        filterId: 961,
        filterQuery: [['ab9022db', '=', true], 'and', ['9d374129', '=', true], 'and', ['eventage', '>=', 20]],
        eventSubItemId: 25130,
        required: 0,
        defaultSelected: 0,
        singleSelected: 0,
        parentItemId: 0,
        requiredItemId: [[]],
        prohibitionItemId: [
            [606, 629],
            [606, 628],
            [628, 612],
            [629, 612],
        ],
        chainItemId: ['629:1', '629:2'],
        itemSubId: 0,
        itemPrice: 1100,
    },
    {
        slotId: 87992,
        itemId: 628,
        maxReservationCount: 25,
        reservationCount: 0,
        priority: 0,
        itemName: '前立腺がん検診',
        itemDescription: '前立腺がん検診は、採血による腫瘍マーカー（PSA）の測定を行います。',
        itemOverview: '',
        filterId: 961,
        filterQuery: [['ab9022db', '=', true], 'and', ['9d374129', '=', true], 'and', ['eventage', '>=', 20]],
        eventSubItemId: 25133,
        required: 0,
        defaultSelected: 0,
        singleSelected: 1,
        parentItemId: 629,
        requiredItemId: [[]],
        prohibitionItemId: [
            [606, 629],
            [606, 628],
            [628, 612],
            [629, 612],
        ],
        chainItemId: ['612:0', '612:1', '628:1', '628:2'],
        itemSubId: 0,
        itemPrice: 2310,
    },
    {
        slotId: 87995,
        itemId: 607,
        maxReservationCount: 50,
        reservationCount: 0,
        priority: 0,
        itemName: '特定健診',
        itemDescription:
            '特定健康診査(特定健診)は、問診、身体測定(身長・体重)、尿検査(尿蛋白・尿糖)、心電図検査、血圧測定、血液検査(血糖・脂質・肝機能・尿酸・貧血・腎機能)を行います。',
        itemOverview: '',
        filterId: 950,
        filterQuery: [['ab9022db', '=', true], 'and', ['9d374129', '=', true], 'and', ['eventage', '>=', 30]],
        eventSubItemId: 25136,
        required: 0,
        defaultSelected: 0,
        singleSelected: 0,
        parentItemId: 0,
        requiredItemId: [[]],
        prohibitionItemId: [
            [606, 629],
            [606, 628],
            [628, 612],
            [629, 612],
        ],
        chainItemId: ['607:1', '607:2'],
        itemSubId: 0,
        itemPrice: 300,
    },
];

export const instituteDummyData = [
    {
        instituteDescription: '施設説明',
        instituteOverview: '施設概要',
        instituteId: 1,
        instituteCode: '001',
        type: '001',
        instituteZipcode: '120-0005',
        institutePrefecture: '施設都道府県',
        instituteCityName: '新宿区',
        instituteTownName: '中落合',
        instituteAddressName: '2-5-1',
        instituteBuilding: '',
        instituteName: '聖母病院',
        instituteTelno: '03-1111-2222',
        instituteImageURL1: 'https://mct.or.jp/cnc_manager/file/mct_image/mainPhoto_senjyu.jpg',
        instituteImageURL2: 'https://www.sbi-efinance.co.jp/developer/wp-content/uploads/2021/11/pixta_63941911_M.jpg',
        instituteImageURL3: 'https://static.amanaimages.com/imgroom/rf_preview640/60002/60002000066.jpg',
        eventInstituteDays: ['1687621623', '1687708023'],
        dentalFlag: 1,
        useMap: 1,
    },
    {
        instituteDescription: '施設説明',
        instituteOverview: '施設概要',
        instituteId: 2,
        instituteCode: '002',
        type: '003',
        instituteZipcode: '163-0490',
        institutePrefecture: '施設都道府県',
        instituteCityName: '新宿区',
        instituteTownName: '西新宿',
        instituteAddressName: '2-1-1',
        instituteBuilding: '新宿三井ﾋﾞﾙ4Ｆ',
        instituteName: '新宿三井ビルクリニック',
        instituteTelno: '03-1111-2222',
        instituteImageURL1: 'https://mct.or.jp/cnc_manager/file/mct_image/mainPhoto_senjyu.jpg',
        instituteImageURL2: 'https://www.sbi-efinance.co.jp/developer/wp-content/uploads/2021/11/pixta_63941911_M.jpg',
        instituteImageURL3: 'https://static.amanaimages.com/imgroom/rf_preview640/60002/60002000066.jpg',
        eventInstituteDays: ['1687621623'],
        dentalFlag: 0,
        useMap: 0,
    },
];
